sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t miguemuba/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true miguemuba/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker"
  env: "Docker-env"
  bucket: "elasticbeanstalk-us-west-1-929283736800"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"